apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rbtcfaucet.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "rbtcfaucet.labels" . | nindent 4 }}
data:
  NODE_ENV: "production"
  PORT: "3000"
  HOSTNAME: "0.0.0.0"
  {{- range $key, $value := .Values.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
