{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "rbtcfaucet.fullname" . }}-env-secrets
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "rbtcfaucet.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreName }}
    kind: SecretStore
  target:
    name: {{ include "rbtcfaucet.fullname" . }}-env-secrets
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: {{ .Values.externalSecrets.secretKey | default "rbtcfaucet-dev" }}
{{- end }}
