{{- if .Values.secrets }}
{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rbtcfaucet.fullname" . }}-env-secrets
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "rbtcfaucet.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets.SECRET_VERIFY_CAPTCHA }}
  SECRET_VERIFY_CAPTCHA: {{ .Values.secrets.SECRET_VERIFY_CAPTCHA | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.NEXT_PUBLIC_SITE_KEY_CAPTCHA }}
  NEXT_PUBLIC_SITE_KEY_CAPTCHA: {{ .Values.secrets.NEXT_PUBLIC_SITE_KEY_CAPTCHA | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.FAUCET_ADDRESS }}
  FAUCET_ADDRESS: {{ .Values.secrets.FAUCET_ADDRESS | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.FAUCET_PRIVATE_KEY }}
  FAUCET_PRIVATE_KEY: {{ .Values.secrets.FAUCET_PRIVATE_KEY | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.REDIS_PASSWORD }}
  REDIS_PASSWORD: {{ .Values.secrets.REDIS_PASSWORD | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.API_KEY }}
  API_KEY: {{ .Values.secrets.API_KEY | b64enc | quote }}
  {{- end }}
{{- end }}
{{- end }}
