{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rbtc-faucet.fullname" . }}-secrets
  labels:
    {{- include "rbtc-faucet.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets.SECRET_VERIFY_CAPTCHA }}
  SECRET_VERIFY_CAPTCHA: {{ .Values.secrets.SECRET_VERIFY_CAPTCHA | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.NEXT_PUBLIC_SITE_KEY_CAPTCHA }}
  NEXT_PUBLIC_SITE_KEY_CAPTCHA: {{ .Values.secrets.NEXT_PUBLIC_SITE_KEY_CAPTCHA | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.FAUCET_ADDRESS }}
  FAUCET_ADDRESS: {{ .Values.secrets.FAUCET_ADDRESS | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.FAUCET_PRIVATE_KEY }}
  FAUCET_PRIVATE_KEY: {{ .Values.secrets.FAUCET_PRIVATE_KEY | b64enc | quote }}
  {{- end }}
{{- end }}
