apiVersion: v1
kind: Service
metadata:
  name: {{ include "rbtcfaucet.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "rbtcfaucet.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
    - port: {{ .Values.service.httpsPort }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: https
  selector:
    {{- include "rbtcfaucet.selectorLabels" . | nindent 4 }}