nameOverride: ""
fullnameOverride: "rbtcfaucet"

namespace: rbtcfaucet-dev

image:
  # repository is set in values-dev.yaml for dev
  tag: latest
  pullPolicy: Always

redis:
  image:
    repository: redis
    tag: latest
  port: 6379

replicaCount: 1

resources:
  requests:
    cpu: "250m"
  limits:
    cpu: "500m"

redisResources:
  requests:
    cpu: "250m"
  limits:
    cpu: "500m"

service:
  type: LoadBalancer
  port: 80
  httpsPort: 443
  targetPort: 3000
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"

ingress:
  enabled: true
  className: alb
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: instance
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70

externalSecrets:
  enabled: false  # Set to true after installing External Secrets Operator
  secretStoreName: aws-secrets-manager
  secretKey: "rbtcfaucet-dev"
  serviceAccountName: "external-secrets-sa"
  region: us-east-1
  refreshInterval: 5m

externalDns:
  enabled: true
  serviceAccountName: external-dns
  # txtOwnerId and domainFilters are set in values-dev.yaml for dev

securityContext:
  runAsNonRoot: true
  fsGroup: 1000

containerSecurityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000

redisSecurityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  runAsUser: 999
  runAsGroup: 999

labels:
  app.kubernetes.io/created-by: platform-eng
  app.kubernetes.io/type: app

serviceAccount:
  create: false
  annotations: {}
  name: ""