image:
  repository: 192930478100.dkr.ecr.us-east-2.amazonaws.com/rbtcfaucet-dev
  tag: latest

namespace: rbtcfaucet-dev

ingress:
  enabled: true
  className: alb
  hosts:
    - host: faucet-dev.rootstock.io
      paths:
        - path: /
          pathType: Prefix
  annotations: {}
