image:
  repository: 192930478100.dkr.ecr.us-east-2.amazonaws.com/rbtcfaucet-dev
  tag: latest

namespace: rbtcfaucet-dev

ingress:
  enabled: false
  wafAclArn: "arn:aws:wafv2:us-east-2:192930478100:regional/webacl/k8sfaucet-waf-blocking/04f5a013-1d3a-4d6b-93da-e78c9ee4d81b"

targetGroupBinding:
  enabled: true
  targetGroupArn: "arn:aws:elasticloadbalancing:us-east-2:192930478100:targetgroup/faucet-cluster-api/cea46137092eb9ab"
